import type { Metadata } from 'next'

// packages imports
import { RootLayout } from '@repo/ui/src/components/layout/RootLayout'
import { Footer } from '@repo/ui/src/components/Footer'

// project imports
import { SocialLink } from '@/components/SocialLink'
import { SimpleNavigationLink } from '@/components/navigation/SimpleNavigationLink'
import { MainNavigationBar } from '@/components/navigation/MainNavigationBar'

import './globals.css'
import '@repo/ui/styles/tailwind.css'
import '@repo/ui/styles/tailwind.css'
import { FooterCopyright } from '@/components/FooterCopyright'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang='en'>
      <body className='flex min-h-full flex-col'>
        <RootLayout
          navigationChildren={<MainNavigationBar />}
          footerChildren={
            <Footer
              SocialLinkComponent={SocialLink}
              NavigationLinkComponent={SimpleNavigationLink}
            >
              <FooterCopyright />
            </Footer>
          }
        >
          {children}
        </RootLayout>
      </body>
    </html>
  )
}
